### ISSUE TITLE
"docker pull rosindustrial/core" ends up with "not found" error

### ISSUE THREAD

**Issue by 130s** [ros-industrial/docker#15]
Not sure if there's anything missing on my side, but I ran the pull command as noted in https://hub.docker.com/r/rosindustrial/core/ then get this error.
```
$ docker pull rosindustrial/core
Using default tag: latest
Error response from daemon: manifest for rosindustrial/core:latest not found
```

**Comment by mathias-luedtke** [comment]
`rosindustrial/core` does not have a `latest` [tag](https://hub.docker.com/r/rosindustrial/core/tags/), only `indigo` and `kinetic`.
`docker pull rosindustrial/core:kinetic` works.

**Comment by 130s** [comment]
Thanks. Now I can download tags.

I assume pulling `tag`s  a common sense for docker but would be still nice if there's a bit more minimal info, so opened #16.
