### ISSUE TITLE
NO_PUBKEY F42ED6FBAB17C654

### ISSUE THREAD

**Issue by 130s** [ros-industrial/docker#27]
On our private repo I get this error.
```
++ docker pull rosindustrial/ci:kinetic-xenial
:
++ sudo apt-get update -qq
++ apt-get update -qq
W: GPG error: http://packages.ros.org/ros/ubuntu xenial InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY F42ED6FBAB17C654
W: The repository 'http://packages.ros.org/ros/ubuntu xenial InRelease' is not signed.
```

Likely related to [discourse.ros.org#9454](https://discourse.ros.org/t/new-gpg-keys-deployed-for-packages-ros-org/9454).

**Comment by mathias-luedtke** [comment]
Yep, the Dockerfiles need to get regenerated. (using [sync.sh](https://github.com/ros-industrial/docker/blob/master/ci/sync.sh)).
