### ISSUE TITLE
Delete ci repository

### ISSUE THREAD

**Issue by mathias-luedtke** [ros-industrial/docker#42]
With the latest changes (https://github.com/ros-industrial/industrial_ci/pull/558) industrial_ci does not use Dockerfiles anymore, but can be used on top of any Debian-based Docker image.

In addtion, the current CI images are outdated and some builds fail.
Only `rosindustrial/ci:kinetic-xenial-shadow-fixed` and `rosindustrial/ci:jade-trusty-shadow-fixed
` have been pulled recently.
So I would like to remove the ci repository.

I could just remove the stale images for now.
Or we wait until the images get removed by the Docker retention policy (mid-2021?).

**Comment by mathias-luedtke** [comment]
> Only rosindustrial/ci:kinetic-xenial-shadow-fixed and rosindustrial/ci:jade-trusty-shadow-fixed have been pulled recently.

Someone seems to have just started a CI job that uses these images ;)

**Comment by Levi-Armstrong** [comment]
Sorry I not familiar with the change to industrial_ci, but we are still using docker images for noether and tesseract from here. Thought because of the size we mostly host the docker file here and have to manually build and push to docker hub because the automated build runs out of space.

**Comment by mathias-luedtke** [comment]
>  but we are still using docker images for noether and tesseract from here.

I do not intend to delete them.. just the outdated CI ones..

> Someone seems to have just started a CI job that uses these images ;)

I think this was triggered by merging #41..
So nobody is using them actively.

**Comment by Levi-Armstrong** [comment]
Ah, sounds good.

**Comment by mathias-luedtke** [comment]
All images went stale and therefore I deleted the repository.
